# Generated by Django 2.0.6 on 2018-06-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180528_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id']},
        ),
    ]
